services:
  json-crud-service:
    build: .
    container_name: json-crud-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=json-crud"
      - "service=api"

networks:
  default:
    name: json-crud-network
